# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RouteBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RouteBoard
  pod 'OpenCV'

  target 'RouteBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RouteBoardUITests' do
    # Pods for testing
  end

end
