services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - USER=SA
      - MSSQL_SA_PASSWORD=Passw0rd_
    volumes:
      - /var/mssql-data:/var/opt/mssql
    ports:
      - "1433:1433"
    container_name: alpinity-api-db
  
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000:10000"
    volumes:
      - /var/azurite-data:/data
    container_name: alpinity-api-azurite
