services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd_
      - POSTGRES_DB=alpinity
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: alpinity-api-db

volumes:
  pgdata:
  azuritedata:
