services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - USER=SA
      - MSSQL_SA_PASSWORD=Passw0rd_
    volumes:
      - /var/mssql-data:/var/opt/mssql
    ports:
      - "1433:1433"
    container_name: alpinity-api-db
volumes:
  db-data: