// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  formDataBodySerializer,
} from "@hey-api/client-fetch";
import type {
  PostApiAuthenticationLoginData,
  PostApiAuthenticationLoginResponse,
  PostApiAuthenticationLoginError,
  PostApiAuthenticationRegisterData,
  PostApiAuthenticationRegisterResponse,
  PostApiAuthenticationRegisterError,
  PostApiAuthenticationAuthenticatedData,
  PostApiAuthenticationAuthenticatedError,
  PostApiAuthenticationMeData,
  PostApiAuthenticationMeResponse,
  PostApiAuthenticationMeError,
  GetApiCragByIdData,
  GetApiCragByIdResponse,
  GetApiCragByIdError,
  PostApiCragData,
  PostApiCragResponse,
  PostApiCragError,
  GetApiMapExploreData,
  GetApiMapExploreResponse,
  GetApiMapExploreError,
  GetApiMapWeatherByCragIdData,
  GetApiMapWeatherByCragIdResponse,
  GetApiMapWeatherByCragIdError,
  PostApiMapGlobeData,
  PostApiMapGlobeResponse,
  PostApiMapGlobeError,
  GetApiMapGlobeSectorsByCragIdData,
  GetApiMapGlobeSectorsByCragIdResponse,
  GetApiMapGlobeSectorsByCragIdError,
  GetApiRouteByIdData,
  GetApiRouteByIdResponse,
  GetApiRouteByIdError,
  PostApiRouteData,
  PostApiRouteResponse,
  PostApiRouteError,
  PostAddPhotoData,
  PostAddPhotoError,
  PostApiSearchData,
  PostApiSearchResponse,
  PostApiSearchError,
  PostApiSectorData,
  PostApiSectorResponse,
  PostApiSectorError,
  GetApiSectorByIdData,
  GetApiSectorByIdResponse,
  GetApiSectorByIdError,
  GetApiSectorSectorCragByIdData,
  GetApiSectorSectorCragByIdResponse,
  GetApiSectorSectorCragByIdError,
  PostApiUserLogAscentData,
  PostApiUserLogAscentError,
  GetApiUserSearchHistoryData,
  GetApiUserSearchHistoryResponse,
  GetApiUserSearchHistoryError,
  GetApiUserRecentlyAscendedRoutesData,
  GetApiUserRecentlyAscendedRoutesResponse,
  GetApiUserRecentlyAscendedRoutesError,
  GetApiUserUserByProfileUserIdData,
  GetApiUserUserByProfileUserIdResponse,
  GetApiUserUserByProfileUserIdError,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const postApiAuthenticationLogin = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthenticationLoginData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostApiAuthenticationLoginResponse,
    PostApiAuthenticationLoginError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Authentication/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const postApiAuthenticationRegister = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthenticationRegisterData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiAuthenticationRegisterResponse,
    PostApiAuthenticationRegisterError,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Authentication/register",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

export const postApiAuthenticationAuthenticated = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthenticationAuthenticatedData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<unknown, PostApiAuthenticationAuthenticatedError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Authentication/authenticated",
    ...options,
  });
};

export const postApiAuthenticationMe = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthenticationMeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostApiAuthenticationMeResponse,
    PostApiAuthenticationMeError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Authentication/me",
    ...options,
  });
};

export const getApiCragById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiCragByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetApiCragByIdResponse, GetApiCragByIdError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Crag/{id}",
    ...options,
  });
};

export const postApiCrag = <ThrowOnError extends boolean = false>(options?: Options<PostApiCragData, ThrowOnError>) => {
  return (options?.client ?? _heyApiClient).post<PostApiCragResponse, PostApiCragError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Crag",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const getApiMapExplore = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiMapExploreData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<GetApiMapExploreResponse, GetApiMapExploreError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Map/explore",
    ...options,
  });
};

export const getApiMapWeatherByCragId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMapWeatherByCragIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMapWeatherByCragIdResponse,
    GetApiMapWeatherByCragIdError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Map/weather/{cragId}",
    ...options,
  });
};

export const postApiMapGlobe = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiMapGlobeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<PostApiMapGlobeResponse, PostApiMapGlobeError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Map/globe",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const getApiMapGlobeSectorsByCragId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiMapGlobeSectorsByCragIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiMapGlobeSectorsByCragIdResponse,
    GetApiMapGlobeSectorsByCragIdError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Map/globe/sectors/{cragId}",
    ...options,
  });
};

export const getApiRouteById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiRouteByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetApiRouteByIdResponse, GetApiRouteByIdError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Route/{id}",
    ...options,
  });
};

export const postApiRoute = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiRouteData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<PostApiRouteResponse, PostApiRouteError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Route",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const postAddPhoto = <ThrowOnError extends boolean = false>(
  options: Options<PostAddPhotoData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<unknown, PostAddPhotoError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/addPhoto",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const postApiSearch = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiSearchData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<PostApiSearchResponse, PostApiSearchError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const postApiSector = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSectorData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<PostApiSectorResponse, PostApiSectorError, ThrowOnError>({
    ...formDataBodySerializer,
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Sector",
    ...options,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
  });
};

export const getApiSectorById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSectorByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<GetApiSectorByIdResponse, GetApiSectorByIdError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Sector/{id}",
    ...options,
  });
};

export const getApiSectorSectorCragById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSectorSectorCragByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiSectorSectorCragByIdResponse,
    GetApiSectorSectorCragByIdError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/Sector/sectorCrag/{id}",
    ...options,
  });
};

export const postApiUserLogAscent = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiUserLogAscentData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<unknown, PostApiUserLogAscentError, ThrowOnError>({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/User/logAscent",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const getApiUserSearchHistory = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiUserSearchHistoryData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiUserSearchHistoryResponse,
    GetApiUserSearchHistoryError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/User/searchHistory",
    ...options,
  });
};

export const getApiUserRecentlyAscendedRoutes = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiUserRecentlyAscendedRoutesData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetApiUserRecentlyAscendedRoutesResponse,
    GetApiUserRecentlyAscendedRoutesError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/User/recentlyAscendedRoutes",
    ...options,
  });
};

export const getApiUserUserByProfileUserId = <ThrowOnError extends boolean = false>(
  options: Options<GetApiUserUserByProfileUserIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetApiUserUserByProfileUserIdResponse,
    GetApiUserUserByProfileUserIdError,
    ThrowOnError
  >({
    security: [
      {
        name: "Authorization",
        type: "apiKey",
      },
    ],
    url: "/api/User/user/{profileUserId}",
    ...options,
  });
};
