// This file is auto-generated by @hey-api/openapi-ts

export type AllRoutePhotoDto = {
  id: string;
  routeId: string;
  image: PhotoDto;
  pathLine: PhotoDto;
  combinedPhoto: PhotoDto;
};

export type AscentCountDto = {
  ascentType?: AscentType;
  count?: number;
};

export type AscentDto = {
  climbTypes?: Array<ClimbType> | null;
  rockTypes?: Array<RockType> | null;
  holdTypes?: Array<HoldType> | null;
  id?: string;
  ascentDate?: string | null;
  notes?: string | null;
  ascentType?: AscentType;
  numberOfAttempts?: number | null;
  proposedGrade?: ClimbingGrade;
  rating?: number | null;
  userId?: string;
  username?: string | null;
  userProfilePhotoUrl?: string | null;
};

export type AscentType = "Onsight" | "Flash" | "Redpoint" | "Aid";

export type ClimbType = "Endurance" | "Powerful" | "Technical";

export type ClimbingGrade =
  | "F_1"
  | "F_2"
  | "F_3"
  | "F_4a"
  | "F_4b"
  | "F_4c"
  | "F_5a"
  | "F_5b"
  | "F_5c"
  | "F_6a"
  | "F_6a_plus"
  | "F_6b"
  | "F_6b_plus"
  | "F_6c"
  | "F_6c_plus"
  | "F_7a"
  | "F_7a_plus"
  | "F_7b"
  | "F_7b_plus"
  | "F_7c"
  | "F_7c_plus"
  | "F_8a"
  | "F_8a_plus"
  | "F_8b"
  | "F_8b_plus"
  | "F_8c"
  | "F_8c_plus"
  | "F_9a"
  | "F_9a_plus"
  | "F_9b"
  | "F_9b_plus"
  | "F_9c"
  | "F_9c_plus"
  | "F_10a"
  | "PROJECT";

export type ClimbingGradeAscentCountDto = {
  routeType?: RouteType;
  gradeCount?: Array<GradeCountDto> | null;
};

export type CragDetailedDto = {
  id?: string;
  name?: string | null;
  description?: string | null;
  location?: PointDto;
  locationName?: string | null;
  sectors?: Array<SectorDetailedDto> | null;
  photos?: Array<PhotoDto> | null;
  canModify?: boolean;
};

export type CreateRouteCommand = {
  name: string | null;
  description?: string | null;
  grade?: ClimbingGrade;
  routeType?: Array<RouteType> | null;
  length?: number | null;
  sectorId: string;
};

export type CurrentWeatherDto = {
  time?: string | null;
  interval?: number;
  temperature2m?: number;
  relativeHumidity2m?: number;
  windSpeed10m?: number;
  windDirection10m?: number;
  weatherCode?: number;
};

export type CustomProblemDetailsResponse = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  errors?: Array<ErrorInfoDto> | null;
  [key: string]:
    | unknown
    | (string | null)
    | (string | null)
    | (number | null)
    | (string | null)
    | (string | null)
    | (Array<ErrorInfoDto> | null)
    | undefined;
};

export type DailyWeatherDto = {
  date?: string | null;
  weatherCode?: number;
  temperature2mMax?: number;
  temperature2mMin?: number;
  apparentTemperatureMax?: number;
  apparentTemperatureMin?: number;
  sunrise?: string | null;
  sunset?: string | null;
  uvIndexMax?: number;
  precipitationSum?: number;
  precipitationProbabilityMax?: number;
  windSpeed10mMax?: number;
  windDirection10mDominant?: number;
};

export type DetectRoutePhotoDto = {
  id: string;
  routeId?: string;
  image?: PhotoDto;
  pathLine?: PhotoDto;
};

export type DownloadCragResponse = {
  id?: string;
  name?: string | null;
  description?: string | null;
  locationName?: string | null;
  sectors?: Array<DownloadSectorResponse> | null;
  photos?: Array<PhotoDto> | null;
};

export type DownloadRouteResponse = {
  id: string;
  name: string | null;
  description?: string | null;
  grade?: ClimbingGrade;
  createdAt?: string | null;
  routeType?: Array<RouteType> | null;
  length?: number | null;
  sectorId: string;
  sectorName: string | null;
  cragId: string;
  cragName: string | null;
  routePhotos?: Array<AllRoutePhotoDto> | null;
  routeCategories?: RouteCategoriesDto;
};

export type DownloadSectorResponse = {
  id: string;
  name: string | null;
  description?: string | null;
  location?: PointDto;
  photos?: Array<PhotoDto> | null;
  routes?: Array<DownloadRouteResponse> | null;
  cragId?: string;
  cragName?: string | null;
};

export type EditRouteCommand = {
  name?: string | null;
  description?: string | null;
  grade?: ClimbingGrade;
  routeType?: Array<RouteType> | null;
  length?: number | null;
  photosToRemove?: Array<string> | null;
};

export type ErrorInfoDto = {
  statusCode?: number;
  message?: string | null;
};

export type ExploreDto = {
  id: string;
  cragId?: string | null;
  cragName?: string | null;
  cragDescription?: string | null;
  location?: PointDto;
  locationName?: string | null;
  photo?: PhotoDto;
  sectorsCount?: number | null;
  routesCount?: number | null;
  ascentsCount?: number | null;
};

export type GetGlobeCommand = {
  northEast?: PointDto;
  southWest?: PointDto;
};

export type GlobeResponseDto = {
  id?: string;
  name?: string | null;
  imageUrl?: string | null;
  location?: PointDto;
};

export type GlobeSectorResponseDto = {
  id?: string;
  cragId?: string;
  name?: string | null;
  imageUrl?: string | null;
  location?: PointDto;
};

export type GradeCountDto = {
  climbingGrade?: ClimbingGrade;
  count?: number;
};

export type HoldType = "Crack" | "Crimps" | "Slopers" | "Pinches" | "Jugs" | "Pockets";

export type HourlyWeatherDto = {
  time?: string | null;
  temperature2m?: number;
  relativeHumidity2m?: number;
  rain?: number;
  weatherCode?: number;
  windSpeed10m?: number;
  windDirection10m?: number;
  precipitationProbability?: number;
};

export type LogAscentCommand = {
  routeId: string;
  ascentDate?: string;
  notes?: string | null;
  climbTypes?: Array<ClimbType> | null;
  rockTypes?: Array<RockType> | null;
  holdTypes?: Array<HoldType> | null;
  ascentType?: AscentType;
  numberOfAttempts?: number | null;
  proposedGrade?: ClimbingGrade;
  rating?: number | null;
};

export type LoggedInUserDto = {
  id: string;
  email: string | null;
  username: string | null;
  profilePhoto?: PhotoDto;
  role?: UserRole;
  token?: string | null;
};

export type LoginCommand = {
  emailOrUsername: string | null;
  password: string | null;
};

export type PaginatedUsersDto = {
  users?: Array<UserRestrictedDto> | null;
  totalCount?: number;
};

export type PhotoDto = {
  id: string;
  url: string | null;
  takenAt?: string | null;
};

export type PointDto = {
  latitude: number;
  longitude: number;
};

export type RecentlyAscendedRouteDto = {
  id: string;
  name: string | null;
  description?: string | null;
  grade?: ClimbingGrade;
  length?: number | null;
  sectorId: string;
  sectorName: string | null;
  cragId: string;
  cragName: string | null;
  routePhotos?: Array<RoutePhotoDto> | null;
  ascentsCount?: number;
};

export type RockType = "Vertical" | "Overhang" | "Roof" | "Slab" | "Arete" | "Dihedral";

export type RouteCategoriesDto = {
  climbTypes?: Array<ClimbType> | null;
  rockTypes?: Array<RockType> | null;
  holdTypes?: Array<HoldType> | null;
};

export type RouteDetailedDto = {
  id: string;
  name: string | null;
  description?: string | null;
  grade?: ClimbingGrade;
  createdAt?: string | null;
  routeType?: Array<RouteType> | null;
  length?: number | null;
  sectorId: string;
  sectorName: string | null;
  cragId: string;
  cragName: string | null;
  routePhotos?: Array<RoutePhotoDto> | null;
  routeCategories?: RouteCategoriesDto;
  ascents?: Array<AscentDto> | null;
  canModify?: boolean;
};

export type RoutePhotoDto = {
  id: string;
  routeId?: string;
  combinedPhoto?: PhotoDto;
};

export type RouteType =
  | "Boulder"
  | "Sport"
  | "Trad"
  | "MultiPitch"
  | "Ice"
  | "BigWall"
  | "Mixed"
  | "Aid"
  | "ViaFerrata";

export type RouteTypeAscentCountDto = {
  routeType?: RouteType;
  ascentCount?: Array<AscentCountDto> | null;
};

export type SearchQueryCommand = {
  query: string | null;
  page?: number;
  pageSize?: number;
};

export type SearchResultDto = {
  id?: string;
  entityType?: SearchResultItemType;
  photo?: PhotoDto;
  cragLocation?: PointDto;
  cragId?: string | null;
  cragName?: string | null;
  cragRoutesCount?: number | null;
  cragSectorsCount?: number | null;
  sectorName?: string | null;
  sectorId?: string | null;
  sectorCragId?: string | null;
  sectorCragName?: string | null;
  sectorRoutesCount?: number | null;
  routeId?: string | null;
  routeDifficulty?: ClimbingGrade;
  routeName?: string | null;
  routeAscentsCount?: number | null;
  routeSectorId?: string | null;
  routeSectorName?: string | null;
  routeCragId?: string | null;
  routeCragName?: string | null;
  ascentsCount?: number | null;
  profileUserId?: string | null;
  profileUsername?: string | null;
};

export type SearchResultItemType = "Crag" | "Sector" | "Route" | "UserProfile";

export type SectorDetailedDto = {
  id: string;
  name: string | null;
  description?: string | null;
  location?: PointDto;
  photos?: Array<PhotoDto> | null;
  routes?: Array<SectorRouteDto> | null;
  cragId?: string;
  cragName?: string | null;
  canModify?: boolean;
};

export type SectorRouteDto = {
  id: string;
  name: string | null;
  description?: string | null;
  grade?: ClimbingGrade;
  createdAt?: string | null;
  routeType?: Array<RouteType> | null;
  length?: number | null;
  routeCategories?: RouteCategoriesDto;
  routePhotos?: Array<RoutePhotoDto> | null;
  ascentsCount?: number | null;
};

export type UpdateCragCreatorsDto = {
  userIds?: Array<string> | null;
};

export type UserProfileDto = {
  id?: string;
  username?: string | null;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  profilePhoto?: PhotoDto;
  cragsVisited?: number | null;
  routeTypeAscentCount?: Array<RouteTypeAscentCountDto> | null;
  climbingGradeAscentCount?: Array<ClimbingGradeAscentCountDto> | null;
  photos?: Array<PhotoDto> | null;
};

export type UserRestrictedDto = {
  id?: string;
  username?: string | null;
  firstName?: string | null;
  lastName?: string | null;
};

export type UserRole = "User" | "Admin" | "Creator";

export type WeatherResponseDto = {
  current?: CurrentWeatherDto;
  hourly?: Array<HourlyWeatherDto> | null;
  daily?: Array<DailyWeatherDto> | null;
};

export type PostApiAuthenticationLoginData = {
  body?: LoginCommand;
  path?: never;
  query?: never;
  url: "/api/Authentication/login";
};

export type PostApiAuthenticationLoginErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type PostApiAuthenticationLoginError = PostApiAuthenticationLoginErrors[keyof PostApiAuthenticationLoginErrors];

export type PostApiAuthenticationLoginResponses = {
  /**
   * OK
   */
  200: LoggedInUserDto;
};

export type PostApiAuthenticationLoginResponse =
  PostApiAuthenticationLoginResponses[keyof PostApiAuthenticationLoginResponses];

export type PostApiAuthenticationRegisterData = {
  body?: {
    Email: string;
    Username: string;
    Password: string;
    FirstName?: string;
    LastName?: string;
    DateOfBirth?: string;
    ProfilePhoto?: Blob | File;
    NormalizedEmail?: string;
  };
  path?: never;
  query?: never;
  url: "/api/Authentication/register";
};

export type PostApiAuthenticationRegisterErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Conflict
   */
  409: CustomProblemDetailsResponse;
};

export type PostApiAuthenticationRegisterError =
  PostApiAuthenticationRegisterErrors[keyof PostApiAuthenticationRegisterErrors];

export type PostApiAuthenticationRegisterResponses = {
  /**
   * OK
   */
  200: LoggedInUserDto;
};

export type PostApiAuthenticationRegisterResponse =
  PostApiAuthenticationRegisterResponses[keyof PostApiAuthenticationRegisterResponses];

export type PostApiAuthenticationAuthenticatedData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Authentication/authenticated";
};

export type PostApiAuthenticationAuthenticatedErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type PostApiAuthenticationAuthenticatedError =
  PostApiAuthenticationAuthenticatedErrors[keyof PostApiAuthenticationAuthenticatedErrors];

export type PostApiAuthenticationAuthenticatedResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiAuthenticationMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Authentication/me";
};

export type PostApiAuthenticationMeErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type PostApiAuthenticationMeError = PostApiAuthenticationMeErrors[keyof PostApiAuthenticationMeErrors];

export type PostApiAuthenticationMeResponses = {
  /**
   * OK
   */
  200: LoggedInUserDto;
};

export type PostApiAuthenticationMeResponse = PostApiAuthenticationMeResponses[keyof PostApiAuthenticationMeResponses];

export type DeleteApiCragByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Crag/{id}";
};

export type DeleteApiCragByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type DeleteApiCragByIdError = DeleteApiCragByIdErrors[keyof DeleteApiCragByIdErrors];

export type DeleteApiCragByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiCragByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Crag/{id}";
};

export type GetApiCragByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiCragByIdError = GetApiCragByIdErrors[keyof GetApiCragByIdErrors];

export type GetApiCragByIdResponses = {
  /**
   * OK
   */
  200: CragDetailedDto;
};

export type GetApiCragByIdResponse = GetApiCragByIdResponses[keyof GetApiCragByIdResponses];

export type PutApiCragByIdData = {
  body?: {
    Id: string;
    Name?: string;
    Description?: string;
    Photos?: Array<Blob | File>;
    LocationName?: string;
    PhotosToRemove?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Crag/{id}";
};

export type PutApiCragByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PutApiCragByIdError = PutApiCragByIdErrors[keyof PutApiCragByIdErrors];

export type PutApiCragByIdResponses = {
  /**
   * OK
   */
  200: CragDetailedDto;
};

export type PutApiCragByIdResponse = PutApiCragByIdResponses[keyof PutApiCragByIdResponses];

export type PostApiCragData = {
  body?: {
    Name: string;
    Description?: string;
    Photos?: Array<Blob | File>;
  };
  path?: never;
  query?: never;
  url: "/api/Crag";
};

export type PostApiCragErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostApiCragError = PostApiCragErrors[keyof PostApiCragErrors];

export type PostApiCragResponses = {
  /**
   * OK
   */
  200: CragDetailedDto;
};

export type PostApiCragResponse = PostApiCragResponses[keyof PostApiCragResponses];

export type PostApiCragByIdPhotoData = {
  body?: {
    Photo?: Blob | File;
  };
  path: {
    id: string;
  };
  query?: {
    CragId?: string;
  };
  url: "/api/Crag/{id}/photo";
};

export type PostApiCragByIdPhotoErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostApiCragByIdPhotoError = PostApiCragByIdPhotoErrors[keyof PostApiCragByIdPhotoErrors];

export type PostApiCragByIdPhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiCragByIdUsersData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Crag/{id}/users";
};

export type GetApiCragByIdUsersErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Forbidden
   */
  403: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiCragByIdUsersError = GetApiCragByIdUsersErrors[keyof GetApiCragByIdUsersErrors];

export type GetApiCragByIdUsersResponses = {
  /**
   * OK
   */
  200: Array<UserRestrictedDto>;
};

export type GetApiCragByIdUsersResponse = GetApiCragByIdUsersResponses[keyof GetApiCragByIdUsersResponses];

export type PutApiCragByIdUsersData = {
  body?: UpdateCragCreatorsDto;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Crag/{id}/users";
};

export type PutApiCragByIdUsersErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Forbidden
   */
  403: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PutApiCragByIdUsersError = PutApiCragByIdUsersErrors[keyof PutApiCragByIdUsersErrors];

export type PutApiCragByIdUsersResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiDownloadCragByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Download/crag/{id}";
};

export type GetApiDownloadCragByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiDownloadCragByIdError = GetApiDownloadCragByIdErrors[keyof GetApiDownloadCragByIdErrors];

export type GetApiDownloadCragByIdResponses = {
  /**
   * OK
   */
  200: DownloadCragResponse;
};

export type GetApiDownloadCragByIdResponse = GetApiDownloadCragByIdResponses[keyof GetApiDownloadCragByIdResponses];

export type GetApiDownloadRouteByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Download/route/{id}";
};

export type GetApiDownloadRouteByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiDownloadRouteByIdError = GetApiDownloadRouteByIdErrors[keyof GetApiDownloadRouteByIdErrors];

export type GetApiDownloadRouteByIdResponses = {
  /**
   * OK
   */
  200: DownloadRouteResponse;
};

export type GetApiDownloadRouteByIdResponse = GetApiDownloadRouteByIdResponses[keyof GetApiDownloadRouteByIdResponses];

export type GetApiMapExploreData = {
  body?: never;
  path?: never;
  query?: {
    latitude?: number;
    longitude?: number;
    radius?: number;
  };
  url: "/api/Map/explore";
};

export type GetApiMapExploreErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type GetApiMapExploreError = GetApiMapExploreErrors[keyof GetApiMapExploreErrors];

export type GetApiMapExploreResponses = {
  /**
   * OK
   */
  200: Array<ExploreDto>;
};

export type GetApiMapExploreResponse = GetApiMapExploreResponses[keyof GetApiMapExploreResponses];

export type GetApiMapWeatherByCragIdData = {
  body?: never;
  path: {
    cragId: string;
  };
  query?: never;
  url: "/api/Map/weather/{cragId}";
};

export type GetApiMapWeatherByCragIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiMapWeatherByCragIdError = GetApiMapWeatherByCragIdErrors[keyof GetApiMapWeatherByCragIdErrors];

export type GetApiMapWeatherByCragIdResponses = {
  /**
   * OK
   */
  200: WeatherResponseDto;
  /**
   * No Content
   */
  204: void;
};

export type GetApiMapWeatherByCragIdResponse =
  GetApiMapWeatherByCragIdResponses[keyof GetApiMapWeatherByCragIdResponses];

export type PostApiMapGlobeData = {
  body?: GetGlobeCommand;
  path?: never;
  query?: never;
  url: "/api/Map/globe";
};

export type PostApiMapGlobeErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type PostApiMapGlobeError = PostApiMapGlobeErrors[keyof PostApiMapGlobeErrors];

export type PostApiMapGlobeResponses = {
  /**
   * OK
   */
  200: Array<GlobeResponseDto>;
};

export type PostApiMapGlobeResponse = PostApiMapGlobeResponses[keyof PostApiMapGlobeResponses];

export type GetApiMapGlobeSectorsByCragIdData = {
  body?: never;
  path: {
    cragId: string;
  };
  query?: never;
  url: "/api/Map/globe/sectors/{cragId}";
};

export type GetApiMapGlobeSectorsByCragIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiMapGlobeSectorsByCragIdError =
  GetApiMapGlobeSectorsByCragIdErrors[keyof GetApiMapGlobeSectorsByCragIdErrors];

export type GetApiMapGlobeSectorsByCragIdResponses = {
  /**
   * OK
   */
  200: Array<GlobeSectorResponseDto>;
};

export type GetApiMapGlobeSectorsByCragIdResponse =
  GetApiMapGlobeSectorsByCragIdResponses[keyof GetApiMapGlobeSectorsByCragIdResponses];

export type DeleteApiRouteByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Route/{id}";
};

export type DeleteApiRouteByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type DeleteApiRouteByIdError = DeleteApiRouteByIdErrors[keyof DeleteApiRouteByIdErrors];

export type DeleteApiRouteByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiRouteByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Route/{id}";
};

export type GetApiRouteByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiRouteByIdError = GetApiRouteByIdErrors[keyof GetApiRouteByIdErrors];

export type GetApiRouteByIdResponses = {
  /**
   * OK
   */
  200: RouteDetailedDto;
};

export type GetApiRouteByIdResponse = GetApiRouteByIdResponses[keyof GetApiRouteByIdResponses];

export type PutApiRouteByIdData = {
  body?: EditRouteCommand;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Route/{id}";
};

export type PutApiRouteByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PutApiRouteByIdError = PutApiRouteByIdErrors[keyof PutApiRouteByIdErrors];

export type PutApiRouteByIdResponses = {
  /**
   * OK
   */
  200: RouteDetailedDto;
};

export type PutApiRouteByIdResponse = PutApiRouteByIdResponses[keyof PutApiRouteByIdResponses];

export type PostApiRouteData = {
  body?: CreateRouteCommand;
  path?: never;
  query?: never;
  url: "/api/Route";
};

export type PostApiRouteErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostApiRouteError = PostApiRouteErrors[keyof PostApiRouteErrors];

export type PostApiRouteResponses = {
  /**
   * OK
   */
  200: RouteDetailedDto;
};

export type PostApiRouteResponse = PostApiRouteResponses[keyof PostApiRouteResponses];

export type PostAddPhotoData = {
  body?: {
    RouteId?: string;
    Photo?: Blob | File;
    LinePhoto?: Blob | File;
    CombinedPhoto?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/addPhoto";
};

export type PostAddPhotoErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostAddPhotoError = PostAddPhotoErrors[keyof PostAddPhotoErrors];

export type PostAddPhotoResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetRouteAscentsByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/routeAscents/{id}";
};

export type GetRouteAscentsByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetRouteAscentsByIdError = GetRouteAscentsByIdErrors[keyof GetRouteAscentsByIdErrors];

export type GetRouteAscentsByIdResponses = {
  /**
   * OK
   */
  200: Array<AscentDto>;
};

export type GetRouteAscentsByIdResponse = GetRouteAscentsByIdResponses[keyof GetRouteAscentsByIdResponses];

export type GetRoutePhotosByRouteIdData = {
  body?: never;
  path: {
    routeId: string;
  };
  query?: never;
  url: "/routePhotos/{routeId}";
};

export type GetRoutePhotosByRouteIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetRoutePhotosByRouteIdError = GetRoutePhotosByRouteIdErrors[keyof GetRoutePhotosByRouteIdErrors];

export type GetRoutePhotosByRouteIdResponses = {
  /**
   * OK
   */
  200: Array<DetectRoutePhotoDto>;
};

export type GetRoutePhotosByRouteIdResponse = GetRoutePhotosByRouteIdResponses[keyof GetRoutePhotosByRouteIdResponses];

export type PostApiSearchData = {
  body?: SearchQueryCommand;
  path?: never;
  query?: never;
  url: "/api/Search";
};

export type PostApiSearchErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type PostApiSearchError = PostApiSearchErrors[keyof PostApiSearchErrors];

export type PostApiSearchResponses = {
  /**
   * OK
   */
  200: Array<SearchResultDto>;
};

export type PostApiSearchResponse = PostApiSearchResponses[keyof PostApiSearchResponses];

export type PostApiSectorData = {
  body?: {
    Name: string;
    Description?: string;
    "Location.Latitude": number;
    "Location.Longitude": number;
    CragId: string;
    Photos?: Array<Blob | File>;
  };
  path?: never;
  query?: never;
  url: "/api/Sector";
};

export type PostApiSectorErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostApiSectorError = PostApiSectorErrors[keyof PostApiSectorErrors];

export type PostApiSectorResponses = {
  /**
   * OK
   */
  200: SectorDetailedDto;
};

export type PostApiSectorResponse = PostApiSectorResponses[keyof PostApiSectorResponses];

export type DeleteApiSectorByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Sector/{id}";
};

export type DeleteApiSectorByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type DeleteApiSectorByIdError = DeleteApiSectorByIdErrors[keyof DeleteApiSectorByIdErrors];

export type DeleteApiSectorByIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiSectorByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Sector/{id}";
};

export type GetApiSectorByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiSectorByIdError = GetApiSectorByIdErrors[keyof GetApiSectorByIdErrors];

export type GetApiSectorByIdResponses = {
  /**
   * OK
   */
  200: SectorDetailedDto;
};

export type GetApiSectorByIdResponse = GetApiSectorByIdResponses[keyof GetApiSectorByIdResponses];

export type PutApiSectorByIdData = {
  body?: {
    Id: string;
    Name?: string;
    Description?: string;
    "Location.Latitude": number;
    "Location.Longitude": number;
    Photos?: Array<Blob | File>;
    PhotosToRemove?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Sector/{id}";
};

export type PutApiSectorByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PutApiSectorByIdError = PutApiSectorByIdErrors[keyof PutApiSectorByIdErrors];

export type PutApiSectorByIdResponses = {
  /**
   * OK
   */
  200: SectorDetailedDto;
};

export type PutApiSectorByIdResponse = PutApiSectorByIdResponses[keyof PutApiSectorByIdResponses];

export type GetApiSectorSectorCragByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/Sector/sectorCrag/{id}";
};

export type GetApiSectorSectorCragByIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiSectorSectorCragByIdError = GetApiSectorSectorCragByIdErrors[keyof GetApiSectorSectorCragByIdErrors];

export type GetApiSectorSectorCragByIdResponses = {
  /**
   * OK
   */
  200: CragDetailedDto;
};

export type GetApiSectorSectorCragByIdResponse =
  GetApiSectorSectorCragByIdResponses[keyof GetApiSectorSectorCragByIdResponses];

export type PostApiSectorByIdPhotoData = {
  body?: {
    Photo?: Blob | File;
  };
  path: {
    id: string;
  };
  query?: {
    SectorId?: string;
  };
  url: "/api/Sector/{id}/photo";
};

export type PostApiSectorByIdPhotoErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostApiSectorByIdPhotoError = PostApiSectorByIdPhotoErrors[keyof PostApiSectorByIdPhotoErrors];

export type PostApiSectorByIdPhotoResponses = {
  /**
   * OK
   */
  200: CragDetailedDto;
};

export type PostApiSectorByIdPhotoResponse = PostApiSectorByIdPhotoResponses[keyof PostApiSectorByIdPhotoResponses];

export type PostApiUserLogAscentData = {
  body?: LogAscentCommand;
  path?: never;
  query?: never;
  url: "/api/User/logAscent";
};

export type PostApiUserLogAscentErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type PostApiUserLogAscentError = PostApiUserLogAscentErrors[keyof PostApiUserLogAscentErrors];

export type PostApiUserLogAscentResponses = {
  /**
   * OK
   */
  200: UserProfileDto;
};

export type PostApiUserLogAscentResponse = PostApiUserLogAscentResponses[keyof PostApiUserLogAscentResponses];

export type GetApiUserSearchHistoryData = {
  body?: never;
  path?: never;
  query?: {
    count?: number;
  };
  url: "/api/User/searchHistory";
};

export type GetApiUserSearchHistoryErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type GetApiUserSearchHistoryError = GetApiUserSearchHistoryErrors[keyof GetApiUserSearchHistoryErrors];

export type GetApiUserSearchHistoryResponses = {
  /**
   * OK
   */
  200: Array<SearchResultDto>;
};

export type GetApiUserSearchHistoryResponse = GetApiUserSearchHistoryResponses[keyof GetApiUserSearchHistoryResponses];

export type GetApiUserRecentlyAscendedRoutesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/User/recentlyAscendedRoutes";
};

export type GetApiUserRecentlyAscendedRoutesErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type GetApiUserRecentlyAscendedRoutesError =
  GetApiUserRecentlyAscendedRoutesErrors[keyof GetApiUserRecentlyAscendedRoutesErrors];

export type GetApiUserRecentlyAscendedRoutesResponses = {
  /**
   * OK
   */
  200: Array<RecentlyAscendedRouteDto>;
};

export type GetApiUserRecentlyAscendedRoutesResponse =
  GetApiUserRecentlyAscendedRoutesResponses[keyof GetApiUserRecentlyAscendedRoutesResponses];

export type GetApiUserUserByProfileUserIdData = {
  body?: never;
  path: {
    profileUserId: string;
  };
  query?: never;
  url: "/api/User/user/{profileUserId}";
};

export type GetApiUserUserByProfileUserIdErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Not Found
   */
  404: CustomProblemDetailsResponse;
};

export type GetApiUserUserByProfileUserIdError =
  GetApiUserUserByProfileUserIdErrors[keyof GetApiUserUserByProfileUserIdErrors];

export type GetApiUserUserByProfileUserIdResponses = {
  /**
   * OK
   */
  200: UserProfileDto;
};

export type GetApiUserUserByProfileUserIdResponse =
  GetApiUserUserByProfileUserIdResponses[keyof GetApiUserUserByProfileUserIdResponses];

export type PutApiUserPhotoData = {
  body?: {
    UserId?: string;
    Photo?: Blob | File;
  };
  path?: never;
  query?: never;
  url: "/api/User/photo";
};

export type PutApiUserPhotoErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
};

export type PutApiUserPhotoError = PutApiUserPhotoErrors[keyof PutApiUserPhotoErrors];

export type PutApiUserPhotoResponses = {
  /**
   * OK
   */
  200: UserProfileDto;
};

export type PutApiUserPhotoResponse = PutApiUserPhotoResponses[keyof PutApiUserPhotoResponses];

export type GetApiUserAllData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    pageSize?: number;
    search?: string;
  };
  url: "/api/User/all";
};

export type GetApiUserAllErrors = {
  /**
   * Bad Request
   */
  400: CustomProblemDetailsResponse;
  /**
   * Unauthorized
   */
  401: CustomProblemDetailsResponse;
  /**
   * Forbidden
   */
  403: CustomProblemDetailsResponse;
};

export type GetApiUserAllError = GetApiUserAllErrors[keyof GetApiUserAllErrors];

export type GetApiUserAllResponses = {
  /**
   * OK
   */
  200: PaginatedUsersDto;
};

export type GetApiUserAllResponse = GetApiUserAllResponses[keyof GetApiUserAllResponses];

export type ClientOptions = {
  baseUrl: "https://192.168.50.175:7244" | "https://localhost:7244" | (string & {});
};
