// <auto-generated />
using System;
using Alpinity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Alpinity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250321120818_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Alpinity.Domain.Entities.Ascent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AscentDate")
                        .HasColumnType("date");

                    b.Property<int?>("AscentType")
                        .HasColumnType("integer");

                    b.Property<string>("ClimbTypes")
                        .HasColumnType("text");

                    b.Property<string>("HoldTypes")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("NumberOfAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("ProposedGrade")
                        .HasColumnType("integer");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("RockTypes")
                        .HasColumnType("text");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Ascents");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Crag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Crags");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.CragWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CragId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeatherData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CragId");

                    b.ToTable("CragWeathers");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CragId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RouteImageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoutePathLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TakenByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserPhotoGalleryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserPhotoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CragId");

                    b.HasIndex("SectorId");

                    b.HasIndex("TakenByUserId");

                    b.HasIndex("UserPhotoGalleryId");

                    b.HasIndex("UserPhotoId")
                        .IsUnique();

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RouteType")
                        .HasColumnType("text");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.RoutePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PathLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("PathLineId")
                        .IsUnique();

                    b.HasIndex("RouteId");

                    b.ToTable("RoutePhotos");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CragId")
                        .HasColumnType("uuid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfileUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SearchingUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CragId");

                    b.HasIndex("ProfileUserId");

                    b.HasIndex("RouteId");

                    b.HasIndex("SearchingUserId");

                    b.HasIndex("SectorId");

                    b.ToTable("SearchHistories");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CragId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CragId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Ascent", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Route", "Route")
                        .WithMany("Ascents")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alpinity.Domain.Entities.User", "User")
                        .WithMany("Ascents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.CragWeather", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Crag", "Crag")
                        .WithMany()
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crag");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Crag", "Crag")
                        .WithMany("Photos")
                        .HasForeignKey("CragId");

                    b.HasOne("Alpinity.Domain.Entities.Sector", "Sector")
                        .WithMany("Photos")
                        .HasForeignKey("SectorId");

                    b.HasOne("Alpinity.Domain.Entities.User", "TakenByUser")
                        .WithMany("TakenPhotos")
                        .HasForeignKey("TakenByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpinity.Domain.Entities.User", "UserPhotoGallery")
                        .WithMany("UserPhotoGallery")
                        .HasForeignKey("UserPhotoGalleryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpinity.Domain.Entities.User", "UserPhoto")
                        .WithOne("ProfilePhoto")
                        .HasForeignKey("Alpinity.Domain.Entities.Photo", "UserPhotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Crag");

                    b.Navigation("Sector");

                    b.Navigation("TakenByUser");

                    b.Navigation("UserPhoto");

                    b.Navigation("UserPhotoGallery");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Route", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Sector", "Sector")
                        .WithMany("Routes")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.RoutePhoto", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Photo", "Image")
                        .WithOne("RouteImage")
                        .HasForeignKey("Alpinity.Domain.Entities.RoutePhoto", "ImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Alpinity.Domain.Entities.Photo", "PathLine")
                        .WithOne("RoutePathLine")
                        .HasForeignKey("Alpinity.Domain.Entities.RoutePhoto", "PathLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alpinity.Domain.Entities.Route", "Route")
                        .WithMany("RoutePhotos")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("PathLine");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.SearchHistory", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Crag", "Crag")
                        .WithMany()
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpinity.Domain.Entities.User", "ProfileUser")
                        .WithMany()
                        .HasForeignKey("ProfileUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpinity.Domain.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Alpinity.Domain.Entities.User", "SearchingUser")
                        .WithMany()
                        .HasForeignKey("SearchingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alpinity.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Crag");

                    b.Navigation("ProfileUser");

                    b.Navigation("Route");

                    b.Navigation("SearchingUser");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Alpinity.Domain.Entities.Crag", "Crag")
                        .WithMany("Sectors")
                        .HasForeignKey("CragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crag");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Crag", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Photo", b =>
                {
                    b.Navigation("RouteImage");

                    b.Navigation("RoutePathLine");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Route", b =>
                {
                    b.Navigation("Ascents");

                    b.Navigation("RoutePhotos");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Alpinity.Domain.Entities.User", b =>
                {
                    b.Navigation("Ascents");

                    b.Navigation("ProfilePhoto");

                    b.Navigation("TakenPhotos");

                    b.Navigation("UserPhotoGallery");
                });
#pragma warning restore 612, 618
        }
    }
}
